### ISSUE TITLE
chrome-specific error stopping page from working 

### ISSUE THREAD

**Issue by webhead3893** [Webcretaire/LiveSplitAnalyzer#1]
![error](https://user-images.githubusercontent.com/71961459/157654452-93510131-f9fe-4323-becc-a32390b10133.png)
this error comes up in the console when a file is dropped in (the actual page just stays on loading)
it only happens on google chrome

**Comment by Webcretaire** [comment]
According to reports from Cerp (thanks Cerp :heart: ) the issue is specifically when using the drag&drop feature on chrome : uploading the file using the "Browse" button works fine
