### ISSUE TITLE
Move time between splits

### ISSUE THREAD

**Issue by Webcretaire** [Webcretaire/LiveSplitAnalyzer#27]
Thanks @cerpintext for the idea

Allow users to specify some amount of time they want to move from one split to the next (or previous maybe, not sure it's useful), maybe for some range of attempts

The idea is if you start implementing a strat at the end of a split (like early control quitout at Claw in Hollow Knight), it is going to lose a bit of time in claw but save more time in the next split, so moving some amount of time between splits will prevent fake golds and stuff

**Comment by cerpintext** [comment]
which files would this be handled in? (since im not really sure of the proj structure atm)

**Comment by Webcretaire** [comment]
The projet what? We need a structure? 😳 
Jokes aside, I'm guessing we would implement this as a button similar to "Fix fake golds" or "Merge into next split" on each individual split in the right tab, in which case it would be in the SplitDisplay component (singular, there is also a plural one), so here: https://github.com/Webcretaire/LiveSplitAnalyzer/blob/master/components/SplitDisplay.vue
But if you're interested in trying to do it yourself or understand how the project works a bit more don't hestitate to ask on Discord (DM or in the dedicated channel on my server) it'll probably be easier and quicker 👍
