### ISSUE TITLE
Deleting fake golds to update best time doesn't stick

### ISSUE THREAD

**Issue by Zannick** [Webcretaire/LiveSplitAnalyzer#70]
I reworked my route and deleted the "best" and "split" times in the LiveSplit splits editor, but later discovered (after I set up a balanced PB for comparison) I still had some fake golds in the splits file. Using the tool, I was able to remove them. However, creating a new comparison still used the old times, and the fake golds all reappeared.

1. Have fake golds (an attempt -1 with the best time) and delete them.
![fake gold to be deleted](https://github.com/Webcretaire/LiveSplitAnalyzer/assets/518709/a5e6e6e5-bc7c-4d13-983e-5f3263ecfd0d)

2. Switching to Comparisons tab and back doesn't make them reappear.
![doesn't reappear if you just switch tabs](https://github.com/Webcretaire/LiveSplitAnalyzer/assets/518709/e8f4c20b-7af5-4618-b427-343c8ecc207d)

3. Creating a new Comparison does (and relies on it). Stats here are shown uncumulative.
![resulted in fake gold reappearing](https://github.com/Webcretaire/LiveSplitAnalyzer/assets/518709/fd10bc02-5ef1-44f5-a3bb-b89c0e88ce76)

Edit: I just attempted to do them separately, and it looks like deleting fake golds and saving doesn't work either...

**Comment by Webcretaire** [comment]
Hello
Thanks for taking the time to file a well documented issue. I managed to reproduce the problem with some of my splits so I can confirm that it is probably a bug, I'll have a look to see if I can fix it

**Comment by Webcretaire** [comment]
Hopefully should be fixed by latest commit, which will be auto-deployed in a few minutes (make sure to force refresh the website with `Ctrl + Maj + R` to be sure you have the latest version)
